export const alertConstantes = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const usuarioConstantes = {
    REGISTER_REQUEST: 'USUARIOS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USUARIOS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USUARIOS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USUARIOS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USUARIOS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USUARIOS_LOGIN_FAILURE',

    LOGOUT: 'USUARIOS_LOGOUT',

    GET_BY_FILTERS_REQUEST: 'USUARIOS_GET_BY_FILTERS_REQUEST',
    GET_BY_FILTERS_SUCCESS: 'USUARIOS_GET_BY_FILTERS_SUCCESS',
    GET_BY_FILTERS_FAILURE: 'USUARIOS_GET_BY_FILTERS_FAILURE',

    DELETE_REQUEST: 'USUARIOS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USUARIOS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USUARIOS_DELETE_FAILURE',
    
    VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
    VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
    VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    VALIDATE_RESET_TOKEN_REQUEST: 'VALIDATE_RESET_TOKEN_REQUEST',
    VALIDATE_RESET_TOKEN_SUCCESS: 'VALIDATE_RESET_TOKEN_SUCCESS',
    VALIDATE_RESET_TOKEN_FAILURE: 'VALIDATE_RESET_TOKEN_FAILURE',

    GET_BY_ID_REQUEST: 'GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'GET_BY_ID_FAILURE',

    UPDATE_REQUEST: 'UPDATE_SUCCESS',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE'
   
};

export const usuarioPedidoDetalleConstantes = {
    AGREGAR_ARTICULO_REQUEST: 'AGREGAR_ARTICULO_REQUEST',
    AGREGAR_ARTICULO_PEDIDO_SUCCESS: 'AGREGAR_ARTICULO_PEDIDO_SUCCESS',
    AGREGAR_ARTICULO_FAILURE: 'AGREGAR_ARTICULO_FAILURE',
    ELIMINAR_ARTICULO_REQUEST: 'ELIMINAR_ARTICULO_REQUEST',
    ELIMINAR_ARTICULO_PEDIDO_SUCCESS: 'ELIMINAR_ARTICULO_PEDIDO_SUCCESS',
    ELIMINAR_ARTICULO_FAILURE: 'ELIMINAR_ARTICULO_FAILURE',
    CAMBIAR_CANTIDAD_ARTICULO_REQUEST: 'CAMBIAR_CANTIDAD_ARTICULO_REQUEST',
    CAMBIAR_CANTIDAD_ARTICULO_DE_UN_PEDIDO_SUCCESS: 'CAMBIAR_CANTIDAD_ARTICULO_DE_UN_PEDIDO_SUCCESS',
    CAMBIAR_CANTIDAD_ARTICULO_FAILURE: 'CAMBIAR_CANTIDAD_ARTICULO_FAILURE'
};

export const usuarioPedidoConstantes = {
    GET_PRECIO_TOTAL_PEDIDO: 'GET_PRECIO_TOTAL_PEDIDO',
    GET_CANTIDAD_ARTICULOS_PEDIDO: 'GET_CANTIDAD_ARTICULOS_PEDIDO'
};

export const marcaConstantes = {
    GET_BY_FILTERS_REQUEST : 'GET_BY_FILTERS_REQUEST',
    GET_BY_FILTERS_SUCCESS: 'GET_BY_FILTERS_SUCCESS',
    GET_BY_FILTERS_FAILURE: 'GET_BY_FILTERS_FAILURE',
    SELECTED_MARCA_SUCCESS: 'SELECTED_MARCA_SUCCESS',
    REMOVE_SELECTED_MARCA_SUCCESS: 'REMOVE_SELECTED_MARCA_SUCCESS'
};

export const empresaConstantes = {
    GET_BY_ID_REQUEST: 'GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'GET_BY_ID_FAILURE',
    
};

export const articuloConstantes = {
    GET_BY_FILTERS_REQUEST : 'GET_BY_FILTERS_REQUEST',
    GET_BY_FILTERS_SUCCESS: 'GET_BY_FILTERS_SUCCESS',
    GET_BY_FILTERS_FAILURE: 'GET_BY_FILTERS_FAILURE',
    GET_COUNT_REQUEST : 'GET_COUNT_REQUEST',
    GET_COUNT_SUCCESS: 'GET_COUNT_SUCCESS',
    GET_COUNT_FAILURE: 'GET_COUNT_FAILURE',
};

